spring:
  application:
    name: order-service
  cloud:
    bus:
      enabled: true
  kafka:
    bootstrap-servers: 192.168.40.152:9092
    consumer:
      group-id: order-service
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: refresh
